Create private repo

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -2,26 +2,9 @@ name: GitHub Actions Demo
 run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
 on: [push]
 jobs:
-  Explore-GitHub-Actions:
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - name: Check out repository code
-        uses: actions/checkout@v3
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
-      - run: echo "🍏 This job's status is ${{ job.status }}."
   Clone_Job:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        
       - name: Set up SSH key
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
@@ -35,8 +18,51 @@ jobs:
       - name: Clone repository
         env:
           REPO_URL: ${{secrets.REPO_URL}}
+          
         run: |
+          REPO_NAME=$(basename "$REPO_URL" .git)
           git clone $REPO_URL
-          # Additional steps as needed
+          echo Repo Name: $REPO_NAME
+          cd $REPO_NAME
+          echo "repo_name=$REPO_NAME" >> "$GITHUB_ENV"
+          echo "repo_folder=$(pwd)" >> "$GITHUB_ENV"
   
 
+      - name: Create new private repo
+        run: |
+          REPO_NAME=${{ env.repo_name }}
+          response=$(curl -sSL -X POST \
+          -H "Accept: application/vnd.github.v3+json" \
+          -H "Authorization: token ${{ secrets.GH_PAT }}" \
+          https://api.github.com/user/repos \
+          -d '{
+            "name": "'"$REPO_NAME"'",
+            "private": true
+          }')
+          echo Response: "$RESPONSE"
+          NEW_REPO_SSH_URL=$(echo "$response" | jq -r .ssh_url)
+          NEW_REPO_HTTPS_URL=$(echo "$response" | jq -r .clone_url)
+          if [[ "$NEW_REPO_HTTPS_URL" == "null" ]]; then
+            echo "Failed to create repository: $response"
+            exit 1
+          fi
+          echo New Repo URLs are: "$NEW_REPO_HTTPS_URL / $NEW_REPO_SSH_URL"  
+          echo "new_repo_ssh_url=$NEW_REPO_SSH_URL" >> "$GITHUB_ENV"
+          echo "new_repo_https_url=$NEW_REPO_HTTPS_URL" >> "$GITHUB_ENV"
+          
+
+      
+      - name: Push content to the new private repo
+        run: |
+            NEW_REPO_HTTPS_URL=${{ env.new_repo_https_url}}
+            echo New repo url is: $NEW_REPO_HTTPS_URL
+            cd ${{env.repo_folder}}
+            echo Folder:$(pwd)
+            echo files: $(ls)
+            echo GIT STATUS: $(git status)
+            git config --global user.name "Your Name"
+            git config --global user.email "your-email@example.com"
+            REPO_URL_WITH_TOKEN=$(echo "$NEW_REPO_HTTPS_URL" | sed "s/https:\/\//https:\/\/${{ secrets.GH_PAT }}@/")
+            echo REPO_URL_WITH_TOKEN: "$REPO_URL_WITH_TOKEN"
+            git remote add newrepo "$REPO_URL_WITH_TOKEN"
+            git push -u newrepo
